service: dio-aws-serverless-lab
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:Get*
            - dynamodb:Scan*
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: 
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/Users

functions:
  createUser:
    handler: src/createUser.createUser
    events:
      - httpApi:
          path: /User
          method: post
  getUser:
    handler: src/getUser.getUser
    events:
      - httpApi:
          path: /User/{id}
          method: get
  getUsers:
    handler: src/getUsers.getUsers
    events:
      - httpApi:
          path: /User
          method: get
  updateUser:
    handler: src/updateUser.updateUser
    events:
      - httpApi:
          path: /User/{id}
          method: put
  deleteUser:
    handler: src/deleteUser.deleteUser
    events:
      - httpApi:
          path: /User/{id}
          method: delete

resources:
  Resources:
    Users:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Users
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
